services:
  db:
    image: postgres
    container_name: taskdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
    volumes:
      - taskdata:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  taskdata: